    	location /engine-rest/ {
        proxy_pass http://10.100.3.45:9090/engine-rest/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /camunda/ {
            proxy_pass http://10.100.3.45:9090/camunda/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /oauth2/ {
            proxy_pass http://10.100.3.45:9090/oauth2/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
