package com.camunda.costcalc;

import java.io.FileInputStream;
import java.util.Properties;
import java.util.logging.Logger;

import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;

import com.camunda.ProcessConstants;

public class Config implements JavaDelegate {

	private final static Logger LOGGER = Logger.getLogger("PROJECT-REQUESTS");

	public static final Properties properties = new Properties();
	public static String RootDir;
	public static String ReportDir;
	public static String ReportName;
	
	public static long dvip;
	public static long tvip;
	public static long qvip;
	public static long bvip;
	public static long pvip;
	public static boolean VipIsExt;
	public static long dnat;
	public static long tnat;
	public static long qnat;
	public static long bnat;
	public static long pnat;
	public static boolean NatIsExt;
	public static long dsrv;
	public static long tsrv;
	public static long qsrv;
	public static long bsrv;
	public static long psrv;
	public static boolean SrvIsExt;
	public static long ddb;
	public static long tdb;
	public static long qdb;
	public static long bdb;
	public static long pdb;
	public static boolean DbIsExt;
	public static boolean ienc;
	public static boolean penc;
	public static long dcerp;
	public static long tcerp;
	public static long qcerp;
	public static long bcerp;
	public static long pcerp;
	public static long dceri;	
	public static long tceri;	
	public static long qceri;	
	public static long bceri;	
	public static long pceri;
	public static long cpu1;
	public static long cpu2;
	public static long cpu3;
	public static long memory1;
	public static long memory2;
	public static long memory3;
	public static long hdd1;
	public static long hdd2;
	public static long hdd3;
	public static long database1;
	public static long database2;
	public static long database3;

	public static long dftq;
	public static long tftq;
	public static long qftq;
	public static long bftq;
	public static long pftq;
	public static long dmsq;
	public static long tmsq;
	public static long qmsq;
	public static long bmsq;
	public static long pmsq;

	public static long trs1;
	public static long trs2;
	public static long trs3;
	public static boolean buslog1;
	public static boolean buslog2;
	public static boolean buslog3;
	public static boolean techlog1;
	public static boolean techlog2;
	public static boolean techlog3;

	public static String sla;
	public static String continuity;
	public static long rto;
	public static long rpo;
	public static long archiv;

	public static long vpn1;
	public static long vpn2;
	public static long vpn3;
	public static long ssvpn1;
	public static long ssvpn2;
	public static long ssvpn3;
	public static long llb1;
	public static long llb2;
	public static long llb3;
	
	public static boolean  NurInt;
	public static boolean  NurWin;
	public static boolean  NurSia;
	public static boolean  NurFis;
	public static boolean  NurWan;
	public static boolean  NurPrgDcMpls;
	public static boolean  PrgInt;
	public static boolean  PrgGpe;
	public static boolean  PrgSia;
	
	public static boolean WebFirewall;
	public static boolean ApplicationFirewall;
	public static boolean MiddlewareFirewall;
	public static boolean DatabaseFirewall;
	public static boolean WebApacheReverseProxy;
	public static boolean ApplicationApacheReverseProxy;
	public static boolean MiddlewareApacheReverseProxy;
	public static boolean ApplicationServerActiveActive;
	public static boolean MiddlewareServerActiveActive;
	public static boolean WebEMCAutostart;
	public static boolean ApplicationEMCAutostart;
	public static boolean MiddlewareEMCAutostart;
	public static boolean DatabaseEMCAutostart;
	public static boolean WebVMwareHA;
	public static boolean ApplicationVMwareHA;
	public static boolean MiddlewareVMwareHA;
	public static boolean DatabaseVMwareHA;
	public static boolean OracleDataGuard;
	public static boolean MSSQLCluster;
	public static boolean ApplicationMSWindowsCluster;
	public static boolean MiddlewareMSWindowsCluster;
	public static boolean WebRedHatCluster;
	public static boolean ApplicationRedHatCluster;
	public static boolean MiddlewareRedHatCluster;
	public static boolean ApplicationRedisSentinelCluster;
	public static boolean MiddlewareRedisSentinelCluster;

	public static long tdes1;
	public static long tdes2;
	public static long tdes3;
	public static long tdes4;
	public static long tdes5;
	public static long tdes6;
	public static long pdes1;
	public static long pdes2;
	public static long pdes3;
	public static long pdes4;
	public static long pdes5;
	public static long pdes6;
	public static long prg1;
	public static long prg2;
	public static long prg3;
	public static long prg4;
	public static long prg5;
	public static long prg6;
	public static boolean PrgIsExt;
	public static long dpl1;
	public static long dpl2;
	public static long dpl3;
	public static long dpl4;
	public static long dpl5;
	public static long dpl6;
	public static boolean DplIsExt;
	public static long lic1;
	public static long lic2;
	public static long lic3;
	public static long lic4;
	public static long lic5;
	public static long lic6;
	public static long mtn1;
	public static long mtn2;
	public static long mtn3;
	public static long mtn4;
	public static long mtn5;
	public static long mtn6;

	public static int Eur2Czk;
	public static int VAT;
	public static int VipDeployCost;
	public static int NatDeployCost;
	public static int SrvDeployCost;
	public static int DbDeployCost;
	public static int CertDeployCost;
	public static int EncDeployCost;
	public static int PublicCertCost;
	public static int InternalCertCost;
	public static int CpuBlock;
	public static int MemoryBlock;
	public static int ServerCost;
	public static int VmRatio;
	public static int StorageBlock;
	public static int StorageCost;
	public static int PkiMgmtCost;
	public static int DesignCost;
	public static int ProgramingCost;
	public static int AppDeploymentCost;
	public static int LicenseCost;
	public static int MaintanaceCost;
	public static int MonitoringCost;
	public static int IndividualVpnCost;
	public static int Site2SsiteVpnCostPerMbps;
	public static int LeasedLineCostPerMbps;
	public static int FtqDeployCost;
	public static int MsqDeployCost;

	public static int TransactionCost;
	public static int BusLogCost;
	public static int TechLogCost;

	public static int NurIntCost;
	public static int NurWinCost;
	public static int NurSiaCost;
	public static int NurFisCost;
	public static int NurWanCost;
	public static int NurPrgDcMplsCost;
	public static int PrgIntCost;
	public static int PrgGpeCost;
	public static int PrgSiaCost;

	public static int FirewallRuleCost;
	public static int ApacheReverseProxyCost;
	public static int ApplicationServerActiveActiveCost;
	public static int EMCAutostartCost;
	public static int VMwareHACost;
	public static int OracleDataGuardCost;
	public static int MSSQLClusterCost;
	public static int MSWindowsClusterCost;
	public static int RedHatClusterCost;
	public static int RedisSentinelClusterCost;

	public static int Sla8x5costRatio;
	public static int Sla24x7costRatio;
	public static int IctPassiveCostRatio;
	public static int IctActiveCostRatio;

	public static long tmp;
	public static long capex;
	public static long capexVAT;
	public static long capexCZVAT;
	public static long capex1;
	public static long capex2;
	public static long capex3;
	public static long capex1e;
	public static long capex2e;
	public static long capex3e;
	public static long capex1i;
	public static long capex2i;
	public static long capex3i;
	public static long opex;
	public static long opexVAT;
	public static long opexCZVAT;
	public static long opex1;
	public static long opex2;
	public static long opex3;
	public static long capexopex;
	public static long capexopexVAT;
	public static long capexCZ;
	public static long capex1CZ;
	public static long capex2CZ;
	public static long capex3CZ;
	public static long capex1eCZ;
	public static long capex2eCZ;
	public static long capex3eCZ;
	public static long capex1iCZ;
	public static long capex2iCZ;
	public static long capex3iCZ;
	public static long opexCZ;
	public static long opex1CZ;
	public static long opex2CZ;
	public static long opex3CZ;
	public static long capexopexCZ;
	public static long capexopexCZVAT;

	public void execute(DelegateExecution execution) throws Exception {

		LOGGER.info("Config Start...");
		
		//LOGGER.info("java.class.path: " + System.getProperty("java.class.path"));
		//LOGGER.info("file.separator: " + System.getProperty("file.separator"));
		//LOGGER.info("java.home: " + System.getProperty("java.home"));
		//LOGGER.info("path.separator: " + System.getProperty("path.separator"));
		//LOGGER.info("user.dir: " + System.getProperty("user.dir"));
		//LOGGER.info("user.home: " + System.getProperty("user.home"));
		RootDir = System.getProperty("user.dir") + System.getProperty("file.separator");
		LOGGER.info("RootDir: " + RootDir);
		FileInputStream config = new FileInputStream(RootDir + ProcessConstants.PROJECT_CONFIG);
		properties.load(config);
		ReportDir = RootDir + properties.getProperty("REPORT_DIR");
		LOGGER.info("ReportDir: " + ReportDir);

		dvip = Long.valueOf(properties.getProperty("dvip"));
		tvip = Long.valueOf(properties.getProperty("tvip"));
		qvip = Long.valueOf(properties.getProperty("qvip"));
		pvip = Long.valueOf(properties.getProperty("pvip"));
		VipIsExt = Boolean.valueOf(properties.getProperty("VipIsExt"));
		dnat = Long.valueOf(properties.getProperty("dnat"));
		tnat = Long.valueOf(properties.getProperty("tnat"));
		qnat = Long.valueOf(properties.getProperty("qnat"));
		pnat = Long.valueOf(properties.getProperty("pnat"));
		NatIsExt = Boolean.valueOf(properties.getProperty("NatIsExt"));
		dsrv = Long.valueOf(properties.getProperty("dsrv"));
		tsrv = Long.valueOf(properties.getProperty("tsrv"));
		qsrv = Long.valueOf(properties.getProperty("qsrv"));
		psrv = Long.valueOf(properties.getProperty("psrv"));
		SrvIsExt = Boolean.valueOf(properties.getProperty("SrvIsExt"));
		ddb = Long.valueOf(properties.getProperty("ddb"));
		tdb = Long.valueOf(properties.getProperty("tdb"));
		qdb = Long.valueOf(properties.getProperty("qdb"));
		pdb = Long.valueOf(properties.getProperty("pdb"));
		DbIsExt = Boolean.valueOf(properties.getProperty("DbIsExt"));
		ienc = Boolean.valueOf(properties.getProperty("ienc"));
		penc = Boolean.valueOf(properties.getProperty("penc"));
		dcerp = Long.valueOf(properties.getProperty("dcerp"));
		tcerp = Long.valueOf(properties.getProperty("tcerp"));
		qcerp = Long.valueOf(properties.getProperty("qcerp"));
		pcerp = Long.valueOf(properties.getProperty("pcerp"));
		dceri = Long.valueOf(properties.getProperty("dceri"));
		tceri = Long.valueOf(properties.getProperty("tceri"));
		qceri = Long.valueOf(properties.getProperty("qceri"));
		pceri = Long.valueOf(properties.getProperty("pceri"));
		cpu1 = Long.valueOf(properties.getProperty("cpu1"));
		cpu2 = Long.valueOf(properties.getProperty("cpu2"));
		cpu3 = Long.valueOf(properties.getProperty("cpu3"));
		memory1 = Long.valueOf(properties.getProperty("memory1"));
		memory2 = Long.valueOf(properties.getProperty("memory2"));
		memory3 = Long.valueOf(properties.getProperty("memory3"));
		hdd1 = Long.valueOf(properties.getProperty("hdd1"));
		hdd2 = Long.valueOf(properties.getProperty("hdd2"));
		hdd3 = Long.valueOf(properties.getProperty("hdd3"));
		database1 = Long.valueOf(properties.getProperty("database1"));
		database2 = Long.valueOf(properties.getProperty("database2"));
		database3 = Long.valueOf(properties.getProperty("database3"));
		dftq = Long.valueOf(properties.getProperty("dftq"));
		tftq = Long.valueOf(properties.getProperty("tftq"));
		qftq = Long.valueOf(properties.getProperty("qftq"));
		pftq = Long.valueOf(properties.getProperty("pftq"));
		dmsq = Long.valueOf(properties.getProperty("dmsq"));
		tmsq = Long.valueOf(properties.getProperty("tmsq"));
		qmsq = Long.valueOf(properties.getProperty("qmsq"));
		pmsq = Long.valueOf(properties.getProperty("pmsq"));
		trs1 = Long.valueOf(properties.getProperty("trs1"));
		trs2 = Long.valueOf(properties.getProperty("trs2"));
		trs3 = Long.valueOf(properties.getProperty("trs3"));
		buslog1 = Boolean.valueOf(properties.getProperty("buslog"));
		buslog2 = buslog1;
		buslog3 = buslog1;
		techlog1 = Boolean.valueOf(properties.getProperty("techlog"));
		techlog2 = techlog1;
		techlog3 = techlog1;

		sla = String.valueOf(properties.getProperty("sla"));
		continuity = String.valueOf(properties.getProperty("continuity"));
		rto = Long.valueOf(properties.getProperty("rto"));
		rpo = Long.valueOf(properties.getProperty("rpo"));
		archiv = Long.valueOf(properties.getProperty("archiv"));

		vpn1 = Long.valueOf(properties.getProperty("vpn1"));
		vpn2 = Long.valueOf(properties.getProperty("vpn2"));
		vpn3 = Long.valueOf(properties.getProperty("vpn3"));
		ssvpn1 = Long.valueOf(properties.getProperty("ssvpn1"));
		ssvpn2 = Long.valueOf(properties.getProperty("ssvpn2"));
		ssvpn3 = Long.valueOf(properties.getProperty("ssvpn3"));
		llb1 = Long.valueOf(properties.getProperty("llb1"));
		llb2 = Long.valueOf(properties.getProperty("llb2"));
		llb3 = Long.valueOf(properties.getProperty("llb3"));

		NurInt = Boolean.valueOf(properties.getProperty("NurInt"));
		NurWin = Boolean.valueOf(properties.getProperty("NurWin"));
		NurSia = Boolean.valueOf(properties.getProperty("NurSia"));
		NurFis = Boolean.valueOf(properties.getProperty("NurFis"));
		NurWan = Boolean.valueOf(properties.getProperty("NurWan"));
		NurPrgDcMpls = Boolean.valueOf(properties.getProperty("NurPrgDcMpls"));
		PrgInt = Boolean.valueOf(properties.getProperty("PrgInt"));
		PrgGpe = Boolean.valueOf(properties.getProperty("PrgGpe"));
		PrgSia = Boolean.valueOf(properties.getProperty("PrgSia"));

		WebFirewall = Boolean.valueOf(properties.getProperty("WebFirewall"));
		ApplicationFirewall = Boolean.valueOf(properties.getProperty("ApplicationFirewall"));
		MiddlewareFirewall = Boolean.valueOf(properties.getProperty("MiddlewareFirewall"));
		DatabaseFirewall = Boolean.valueOf(properties.getProperty("DatabaseFirewall"));
		WebApacheReverseProxy = Boolean.valueOf(properties.getProperty("WebApacheReverseProxy"));
		ApplicationApacheReverseProxy = Boolean.valueOf(properties.getProperty("ApplicationApacheReverseProxy"));
		MiddlewareApacheReverseProxy = Boolean.valueOf(properties.getProperty("MiddlewareApacheReverseProxy"));
		ApplicationServerActiveActive = Boolean.valueOf(properties.getProperty("ApplicationServerActiveActive"));
		MiddlewareServerActiveActive = Boolean.valueOf(properties.getProperty("MiddlewareServerActiveActive"));
		WebEMCAutostart = Boolean.valueOf(properties.getProperty("WebEMCAutostart"));
		ApplicationEMCAutostart = Boolean.valueOf(properties.getProperty("ApplicationEMCAutostart"));
		MiddlewareEMCAutostart = Boolean.valueOf(properties.getProperty("MiddlewareEMCAutostart"));
		DatabaseEMCAutostart = Boolean.valueOf(properties.getProperty("DatabaseEMCAutostart"));
		WebVMwareHA = Boolean.valueOf(properties.getProperty("WebVMwareHA"));
		ApplicationVMwareHA = Boolean.valueOf(properties.getProperty("ApplicationVMwareHA"));
		MiddlewareVMwareHA = Boolean.valueOf(properties.getProperty("MiddlewareVMwareHA"));
		DatabaseVMwareHA = Boolean.valueOf(properties.getProperty("DatabaseVMwareHA"));
		OracleDataGuard = Boolean.valueOf(properties.getProperty("OracleDataGuard"));
		MSSQLCluster = Boolean.valueOf(properties.getProperty("MSSQLCluster"));
		ApplicationMSWindowsCluster = Boolean.valueOf(properties.getProperty("ApplicationMSWindowsCluster"));
		MiddlewareMSWindowsCluster = Boolean.valueOf(properties.getProperty("MiddlewareMSWindowsCluster"));
		WebRedHatCluster = Boolean.valueOf(properties.getProperty("WebRedHatCluster"));
		ApplicationRedHatCluster = Boolean.valueOf(properties.getProperty("ApplicationRedHatCluster"));
		MiddlewareRedHatCluster = Boolean.valueOf(properties.getProperty("MiddlewareRedHatCluster"));
		ApplicationRedisSentinelCluster = Boolean.valueOf(properties.getProperty("ApplicationRedisSentinelCluster"));
		MiddlewareRedisSentinelCluster = Boolean.valueOf(properties.getProperty("MiddlewareRedisSentinelCluster"));

		Eur2Czk = Integer.valueOf(properties.getProperty("Eur2Czk"));
		VAT = Integer.valueOf(properties.getProperty("VAT"));
		VipDeployCost = Integer.valueOf(properties.getProperty("VipDeployCost"));
		NatDeployCost = Integer.valueOf(properties.getProperty("NatDeployCost"));
		SrvDeployCost = Integer.valueOf(properties.getProperty("SrvDeployCost"));
		DbDeployCost = Integer.valueOf(properties.getProperty("DbDeployCost"));
		CertDeployCost = Integer.valueOf(properties.getProperty("CertDeployCost"));
		EncDeployCost = Integer.valueOf(properties.getProperty("EncDeployCost"));
		PublicCertCost = Integer.valueOf(properties.getProperty("PublicCertCost"));
		InternalCertCost = Integer.valueOf(properties.getProperty("InternalCertCost"));
		CpuBlock = Integer.valueOf(properties.getProperty("CpuBlock"));
		MemoryBlock = Integer.valueOf(properties.getProperty("MemoryBlock"));
		ServerCost = Integer.valueOf(properties.getProperty("ServerCost"));
		VmRatio = Integer.valueOf(properties.getProperty("VmRatio"));
		StorageBlock = Integer.valueOf(properties.getProperty("StorageBlock"));
		StorageCost = Integer.valueOf(properties.getProperty("StorageCost"));
		PkiMgmtCost = Integer.valueOf(properties.getProperty("PkiMgmtCost"));
		TransactionCost = Integer.valueOf(properties.getProperty("TransactionCost"));
		BusLogCost = Integer.valueOf(properties.getProperty("BusLogCost"));
		TechLogCost = Integer.valueOf(properties.getProperty("TechLogCost"));
		FtqDeployCost = Integer.valueOf(properties.getProperty("FtqDeployCost"));
		MsqDeployCost = Integer.valueOf(properties.getProperty("MsqDeployCost"));

		DesignCost = Integer.valueOf(properties.getProperty("DesignCost"));
		ProgramingCost = Integer.valueOf(properties.getProperty("ProgramingCost"));
		AppDeploymentCost = Integer.valueOf(properties.getProperty("AppDeploymentCost"));
		LicenseCost = Integer.valueOf(properties.getProperty("LicenseCost"));
		MaintanaceCost = Integer.valueOf(properties.getProperty("MaintanaceCost"));
		MonitoringCost = Integer.valueOf(properties.getProperty("MonitoringCost"));
		IndividualVpnCost = Integer.valueOf(properties.getProperty("IndividualVpnCost"));
		Site2SsiteVpnCostPerMbps = Integer.valueOf(properties.getProperty("Site2SsiteVpnCostPerMbps"));
		LeasedLineCostPerMbps = Integer.valueOf(properties.getProperty("LeasedLineCostPerMbps"));
		
		NurIntCost = Integer.valueOf(properties.getProperty("NurIntCost"));
		NurWinCost = Integer.valueOf(properties.getProperty("NurWinCost"));
		NurSiaCost = Integer.valueOf(properties.getProperty("NurSiaCost"));
		NurFisCost = Integer.valueOf(properties.getProperty("NurFisCost"));
		NurWanCost = Integer.valueOf(properties.getProperty("NurWanCost"));
		NurPrgDcMplsCost = Integer.valueOf(properties.getProperty("NurPrgDcMplsCost"));
		PrgIntCost = Integer.valueOf(properties.getProperty("PrgIntCost"));
		PrgGpeCost = Integer.valueOf(properties.getProperty("PrgGpeCost"));
		PrgSiaCost = Integer.valueOf(properties.getProperty("PrgSiaCost"));

		FirewallRuleCost = Integer.valueOf(properties.getProperty("FirewallRuleCost"));
		ApacheReverseProxyCost = Integer.valueOf(properties.getProperty("ApacheReverseProxyCost"));
		ApplicationServerActiveActiveCost = Integer.valueOf(properties.getProperty("ApplicationServerActiveActiveCost"));
		EMCAutostartCost = Integer.valueOf(properties.getProperty("EMCAutostartCost"));
		VMwareHACost = Integer.valueOf(properties.getProperty("VMwareHACost"));
		OracleDataGuardCost = Integer.valueOf(properties.getProperty("OracleDataGuardCost"));
		MSSQLClusterCost = Integer.valueOf(properties.getProperty("MSSQLClusterCost"));
		MSWindowsClusterCost = Integer.valueOf(properties.getProperty("MSWindowsClusterCost"));
		RedHatClusterCost = Integer.valueOf(properties.getProperty("RedHatClusterCost"));
		RedisSentinelClusterCost = Integer.valueOf(properties.getProperty("RedisSentinelClusterCost"));

		tdes1 = Long.valueOf(properties.getProperty("tdes1"));
		tdes2 = Long.valueOf(properties.getProperty("tdes2"));
		tdes3 = Long.valueOf(properties.getProperty("tdes3"));
		tdes4 = Long.valueOf(properties.getProperty("tdes4"));
		tdes5 = Long.valueOf(properties.getProperty("tdes5"));
		tdes6 = Long.valueOf(properties.getProperty("tdes6"));
		pdes1 = Long.valueOf(properties.getProperty("pdes1"));
		pdes2 = Long.valueOf(properties.getProperty("pdes2"));
		pdes3 = Long.valueOf(properties.getProperty("pdes3"));
		pdes4 = Long.valueOf(properties.getProperty("pdes4"));
		pdes5 = Long.valueOf(properties.getProperty("pdes5"));
		pdes6 = Long.valueOf(properties.getProperty("pdes6"));
		prg1 = Long.valueOf(properties.getProperty("prg1"));
		prg2 = Long.valueOf(properties.getProperty("prg2"));
		prg3 = Long.valueOf(properties.getProperty("prg3"));
		prg4 = Long.valueOf(properties.getProperty("prg4"));
		prg5 = Long.valueOf(properties.getProperty("prg5"));
		prg6 = Long.valueOf(properties.getProperty("prg6"));
		PrgIsExt = Boolean.valueOf(properties.getProperty("PrgIsExt"));
		dpl1 = Long.valueOf(properties.getProperty("dpl1"));
		dpl2 = Long.valueOf(properties.getProperty("dpl2"));
		dpl3 = Long.valueOf(properties.getProperty("dpl3"));
		dpl4 = Long.valueOf(properties.getProperty("dpl4"));
		dpl5 = Long.valueOf(properties.getProperty("dpl5"));
		dpl6 = Long.valueOf(properties.getProperty("dpl6"));
		DplIsExt = Boolean.valueOf(properties.getProperty("DplIsExt"));
		lic1 = Long.valueOf(properties.getProperty("lic1"));
		lic2 = Long.valueOf(properties.getProperty("lic2"));
		lic3 = Long.valueOf(properties.getProperty("lic3"));
		lic4 = Long.valueOf(properties.getProperty("lic4"));
		lic5 = Long.valueOf(properties.getProperty("lic5"));
		lic6 = Long.valueOf(properties.getProperty("lic6"));
		mtn1 = Long.valueOf(properties.getProperty("mtn1"));
		mtn2 = Long.valueOf(properties.getProperty("mtn2"));
		mtn3 = Long.valueOf(properties.getProperty("mtn3"));
		mtn4 = Long.valueOf(properties.getProperty("mtn4"));
		mtn5 = Long.valueOf(properties.getProperty("mtn5"));
		mtn6 = Long.valueOf(properties.getProperty("mtn6"));

		Sla8x5costRatio = Integer.valueOf(properties.getProperty("Sla8x5costRatio"));
		Sla24x7costRatio = Integer.valueOf(properties.getProperty("Sla24x7costRatio"));
		IctPassiveCostRatio = Integer.valueOf(properties.getProperty("IctPassiveCostRatio"));
		IctActiveCostRatio = Integer.valueOf(properties.getProperty("IctActiveCostRatio"));

		ReportName = (String) execution.getVariable("ReportName");

		execution.setVariable("dvip", dvip);
		execution.setVariable("tvip", tvip);
		execution.setVariable("qvip", qvip);
		execution.setVariable("bvip", bvip);
		execution.setVariable("pvip", pvip);
		execution.setVariable("VipIsExt", VipIsExt);
		execution.setVariable("dnat", dnat);
		execution.setVariable("tnat", tnat);
		execution.setVariable("qnat", qnat);
		execution.setVariable("bnat", bnat);
		execution.setVariable("pnat", pnat);
		execution.setVariable("natIsExt", NatIsExt);
		execution.setVariable("dsrv", dsrv);
		execution.setVariable("tsrv", tsrv);
		execution.setVariable("qsrv", qsrv);
		execution.setVariable("bsrv", bsrv);
		execution.setVariable("psrv", psrv);
		execution.setVariable("SrvIsExt", SrvIsExt);
		execution.setVariable("ddb", ddb);
		execution.setVariable("tdb", tdb);
		execution.setVariable("qdb", qdb);
		execution.setVariable("bdb", bdb);
		execution.setVariable("pdb", pdb);
		execution.setVariable("DbIsExt", DbIsExt);
		execution.setVariable("ienc", ienc);
		execution.setVariable("penc", penc);
		execution.setVariable("dcerp", dcerp);	
		execution.setVariable("tcerp", tcerp);	
		execution.setVariable("qcerp", qcerp);	
		execution.setVariable("bcerp", bcerp);	
		execution.setVariable("pcerp", pcerp);
		execution.setVariable("dceri", dceri);	
		execution.setVariable("tceri", tceri);	
		execution.setVariable("qceri", qceri);	
		execution.setVariable("bceri", bceri);	
		execution.setVariable("pceri", pceri);
		execution.setVariable("cpu1", cpu1);
		execution.setVariable("cpu2", cpu2);
		execution.setVariable("cpu3", cpu3);
		execution.setVariable("memory1", memory1);		
		execution.setVariable("memory2", memory2);
		execution.setVariable("memory3", memory3);
		execution.setVariable("hdd1", hdd1);
		execution.setVariable("hdd2", hdd2);
		execution.setVariable("hdd3", hdd3);
		execution.setVariable("database1", database1);
		execution.setVariable("database2", database2);
		execution.setVariable("database3", database3);
		
		LOGGER.info("dftq: " + execution.getVariable("dftq"));
		execution.setVariable("dftq", dftq);
		execution.setVariable("tftq", tftq);
		execution.setVariable("qftq", qftq);
		execution.setVariable("bftq", bftq);
		execution.setVariable("pftq", pftq);
		execution.setVariable("dmsq", dmsq);
		execution.setVariable("tmsq", tmsq);
		execution.setVariable("qmsq", qmsq);
		execution.setVariable("bmsq", bmsq);
		execution.setVariable("pmsq", pmsq);

		execution.setVariable("trs1", trs1);
		execution.setVariable("trs2", trs2);
		execution.setVariable("trs3", trs3);
		execution.setVariable("buslog1", buslog1);
		execution.setVariable("buslog2", buslog2);
		execution.setVariable("buslog3", buslog3);
		execution.setVariable("techlog1", techlog1);
		execution.setVariable("techlog2", techlog2);
		execution.setVariable("techlog3", techlog3);

		execution.setVariable("sla", sla);
		execution.setVariable("continuity", continuity);
		execution.setVariable("rto", rto);
		execution.setVariable("rpo", rpo);
		execution.setVariable("archiv", archiv);

		execution.setVariable("vpn1", vpn1);
		execution.setVariable("vpn2", vpn2);
		execution.setVariable("vpn3", vpn3);
		execution.setVariable("ssvpn1", ssvpn1);
		execution.setVariable("ssvpn2", ssvpn2);
		execution.setVariable("ssvpn3", ssvpn3);
		execution.setVariable("llb1", llb1);
		execution.setVariable("llb2", llb2);
		execution.setVariable("llb3", llb3);

		execution.setVariable("NurInt", NurInt);
		execution.setVariable("NurWin", NurWin);
		execution.setVariable("NurSia", NurSia);
		execution.setVariable("NurFis", NurFis);
		execution.setVariable("NurWan", NurWan);
		execution.setVariable("NurPrgDcMpls", NurPrgDcMpls);
		execution.setVariable("PrgInt", PrgInt);
		execution.setVariable("PrgGpe", PrgGpe);
		execution.setVariable("PrgGpe", PrgSia);
		
		execution.setVariable("WebFirewall", WebFirewall);
		execution.setVariable("ApplicationFirewall", ApplicationFirewall);
		execution.setVariable("MiddlewareFirewall", MiddlewareFirewall);
		execution.setVariable("DatabaseFirewall", DatabaseFirewall);
		execution.setVariable("WebApacheReverseProxy", WebApacheReverseProxy);
		execution.setVariable("ApplicationApacheReverseProxy", ApplicationApacheReverseProxy);
		execution.setVariable("MiddlewareApacheReverseProxy", MiddlewareApacheReverseProxy);
		execution.setVariable("ApplicationServerActiveActive", ApplicationServerActiveActive);
		execution.setVariable("MiddlewareServerActiveActive", ApplicationServerActiveActive);
		execution.setVariable("WebEMCAutostart", WebEMCAutostart);
		execution.setVariable("ApplicationEMCAutostart", ApplicationEMCAutostart);
		execution.setVariable("MiddlewareEMCAutostart", MiddlewareEMCAutostart);
		execution.setVariable("DatabaseEMCAutostart", DatabaseEMCAutostart);
		execution.setVariable("WebVMwareHA", WebVMwareHA);
		execution.setVariable("ApplicationVMwareHA", ApplicationVMwareHA);
		execution.setVariable("MiddlewareVMwareHA", MiddlewareVMwareHA);
		execution.setVariable("DatabaseVMwareHA", DatabaseVMwareHA);
		execution.setVariable("OracleDataGuard", OracleDataGuard);
		execution.setVariable("MSSQLCluster", MSSQLCluster);
		execution.setVariable("ApplicationMSWindowsCluster", ApplicationMSWindowsCluster);
		execution.setVariable("MiddlewareMSWindowsCluster", MiddlewareMSWindowsCluster);
		execution.setVariable("WebRedHatCluster", WebRedHatCluster);
		execution.setVariable("ApplicationRedHatCluster", ApplicationRedHatCluster);
		execution.setVariable("MiddlewareRedHatCluster", MiddlewareRedHatCluster);
		execution.setVariable("ApplicationRedisSentinelCluster", ApplicationRedisSentinelCluster);
		execution.setVariable("MiddlewareRedisSentinelCluster", MiddlewareRedisSentinelCluster);
		
		execution.setVariable("tdes1", tdes1);
		execution.setVariable("tdes2", tdes2);
		execution.setVariable("tdes3", tdes3);
		execution.setVariable("tdes4", tdes4);
		execution.setVariable("tdes5", tdes5);
		execution.setVariable("tdes6", tdes6);
		execution.setVariable("pdes1", pdes1);
		execution.setVariable("pdes2", pdes2);
		execution.setVariable("pdes3", pdes3);
		execution.setVariable("pdes4", pdes4);
		execution.setVariable("pdes5", pdes5);
		execution.setVariable("pdes6", pdes6);
		execution.setVariable("prg1", prg1);
		execution.setVariable("prg2", prg2);
		execution.setVariable("prg3", prg3);
		execution.setVariable("prg4", prg4);
		execution.setVariable("prg5", prg5);
		execution.setVariable("prg6", prg6);
		execution.setVariable("PrgIsExt", PrgIsExt);
		execution.setVariable("dpl1", dpl1);
		execution.setVariable("dpl2", dpl2);
		execution.setVariable("dpl3", dpl3);
		execution.setVariable("dpl4", dpl4);
		execution.setVariable("dpl5", dpl5);
		execution.setVariable("dpl6", dpl6);
		execution.setVariable("DplIsExt", DplIsExt);
		execution.setVariable("lic1", lic1);
		execution.setVariable("lic2", lic2);
		execution.setVariable("lic3", lic3);
		execution.setVariable("lic4", lic4);
		execution.setVariable("lic5", lic5);
		execution.setVariable("lic6", lic6);
		execution.setVariable("mtn1", mtn1);
		execution.setVariable("mtn2", mtn2);
		execution.setVariable("mtn3", mtn3);
		execution.setVariable("mtn4", mtn4);
		execution.setVariable("mtn5", mtn5);
		execution.setVariable("mtn6", mtn6);
		
		execution.setVariable("Sla8x5costRatio", Sla8x5costRatio);
		execution.setVariable("Sla24x7costRatio", Sla24x7costRatio);
		execution.setVariable("IctPassiveCostRatio", IctPassiveCostRatio);
		execution.setVariable("IctActiveCostRatio", IctActiveCostRatio);

		execution.setVariable("newcalc", false);

		//LOGGER.info("sla: " + execution.getVariable("sla"));
	}
}
