JDBC_DRIVER = com.mysql.jdbc.Driver
DB_URL = jdbc:mysql://localhost:3306/std
USER = root
PASS = kokos123
REPORT_DIR = out/

dvip = 0
tvip = 0
qvip = 0
bvip = 0
pvip = 0
VipIsExt = true
dnat = 0
tnat = 0
qnat = 0
bnat = 0
pnat = 0
NatIsExt = true
dsrv = 0
tsrv = 0
qsrv = 0
bsrv = 0
psrv = 0
SrvIsExt = true
ddb = 0
tdb = 0
qdb = 0
bdb = 0
pdb = 0
DbIsExt = false
ienc = true
penc = true
dcerp = 0
tcerp = 0
qcerp = 0
bcerp = 0
pcerp = 0
dceri = 0
tceri = 0
qceri = 0
bceri = 0
pceri = 0
cpu1 = 0
cpu2 = 0
cpu3 = 0
memory1 = 0
memory2 = 0
memory3 = 0
hdd1 = 0
hdd2 = 0
hdd3 = 0
database1 = 0
database2 = 0
database3 = 0

dftq = 0
tftq = 0
qftq = 0
bftq = 0
pftq = 0
dmsq = 0
tmsq = 0
qmsq = 0
bmsq = 0
pmsq = 0

trs1 = 0
trs2 = 0
trs3 = 0
buslog = false
techlog = false

sla = 8x5
continuity = passive
rto = 4
rpo = 15
archiv = 10

vpn1 = 0
vpn2 = 0
vpn3 = 0
ssvpn1 = 0
ssvpn2 = 0
ssvpn3 = 0
llb1 = 0
llb2 = 0
llb3 = 0

NurInt = true
NurWin = false
NurSia = false
NurFis = false
NurWan = false
NurPrgDcMpls = true
PrgInt = false
PrgGpe = false
PrgSia = false

WebFirewall = false
ApplicationFirewall = true
MiddlewareFirewall = true
DatabaseFirewall = true
WebApacheReverseProxy = false
ApplicationApacheReverseProxy = false
MiddlewareApacheReverseProxy = false
ApplicationServerActiveActive = false
MiddlewareServerActiveActive = false
WebEMCAutostart = false
ApplicationEMCAutostart = false
MiddlewareEMCAutostart = false
DatabaseEMCAutostart = false
WebVMwareHA = false
ApplicationVMwareHA = false
MiddlewareVMwareHA = false
DatabaseVMwareHA = false
OracleDataGuard = false
MSSQLCluster = false
ApplicationMSWindowsCluster = false
MiddlewareMSWindowsCluster = false
WebRedHatCluster = false
ApplicationRedHatCluster = false
MiddlewareRedHatCluster = false
ApplicationRedisSentinelCluster = false
MiddlewareRedisSentinelCluster = false

tdes1 = 1
tdes2 = 1
tdes3 = 1
tdes4 = 1
tdes5 = 1
tdes6 = 1
pdes1 = 1
pdes2 = 1
pdes3 = 1
pdes4 = 1
pdes5 = 1
pdes6 = 1
prg1 = 0
prg2 = 0
prg3 = 0
prg4 = 0
prg5 = 0
prg6 = 0
PrgIsExt = true
dpl1 = 0
dpl2 = 0
dpl3 = 0
dpl4 = 0
dpl5 = 0
dpl6 = 0
DplIsExt = true
lic1 = 0
lic2 = 0
lic3 = 0
lic4 = 0
lic5 = 0
lic6 = 0
mtn1 = 0
mtn2 = 0
mtn3 = 0
mtn4 = 0
mtn5 = 0
mtn6 = 0

Eur2Czk = 26
VAT = 21
CzEmployeeCost = 307
SkEmployeeCost = 322
ExternalCost = 750

VipDeployCost = 750
NatDeployCost = 100
SrvDeployCost = 400
DbDeployCost = 400
CertDeployCost = 100
EncDeployCost = 400
PublicCertCost = 100
InternalCertCost = 10
FtqDeployCost = 200
MsqDeployCost = 200

CpuBlock = 32
VmRatio = 5
StorageBlock = 1024
MemoryBlock = 750

ServerCost = 9240
StorageCost = 2400
PkiMgmtCost = 100
DesignCost = 800
ProgramingCost = 400
AppDeploymentCost = 300
LicenseCost = 0
MaintanaceCost = 400
MonitoringCost = 400
IndividualVpnCost = 10
Site2SsiteVpnCostPerMbps = 100
LeasedLineCostPerMbps = 1000

TransactionCost = 10
BusLogCost = 10
TechLogCost = 10

NurIntCost = 100
NurWinCost = 100
NurSiaCost = 100
NurFisCost = 100
NurWanCost = 100
NurPrgDcMplsCost = 100
PrgIntCost = 100
PrgGpeCost = 100
PrgSiaCost = 100

FirewallRuleCost = 10
ApacheReverseProxyCost = 10
ApplicationApacheReverseProxyCost = 10
ApplicationServerActiveActiveCost = 10
EMCAutostartCost = 10
VMwareHACost = 10
OracleDataGuardCost = 10
MSSQLClusterCost = 10
MSWindowsClusterCost = 10
RedHatClusterCost = 10
RedisSentinelClusterCost = 10

Sla8x5costRatio = 20
Sla24x7costRatio = 100
IctPassiveCostRatio = 50
IctActiveCostRatio = 100
